apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: external-secrets
  name: external-secrets
  namespace: default
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: external-secrets
  template:
    metadata:
      labels:
        name: external-secrets
        service: external-secrets
    spec:
      serviceAccountName: external-secrets
      securityContext:
        fsGroup: 65534
      containers:
        - image: godaddy/kubernetes-external-secrets:3.1.0
          resources:
            limits:
              cpu: 50m
              memory: 150M
            requests:
              cpu: 25m
              memory: 100M
          imagePullPolicy: Always
          name: external-secrets
          env:
            - name: AWS_REGION
              value: eu-west-1
            - name: POLLER_INTERVAL_MILLISECONDS
              value: "120000"