---
# Source: reloader/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reloader
  name: reloader
  namespace: default
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: reloader
  template:
    metadata:
      labels:
        app: reloader
    spec:
      containers:
      - env:
        image: stakater/reloader:v0.0.118
        resources:
          limits:
            cpu: 50m
            memory: 25M
          requests:
            cpu: 25m
            memory: 15M
        imagePullPolicy: IfNotPresent
        name: reloader
        args:
      serviceAccountName: reloader
